import AuthLayout from '@/app/layout/AuthLayout'
import { Metadata, Viewport } from 'next'

export const metadata: Metadata = {
  title: 'هتل ارگ جدید یزد',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Also supported but less commonly used
  // interactiveWidget: 'resizes-visual',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <AuthLayout>{children}</AuthLayout>
}
