import type { Metadata, Viewport } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Providers from './providers'

const iranSans = localFont({
  src: [
    {
      path: './fonts/IRANSansWeb.woff',
      weight: '400',
    },
    {
      path: './fonts/IRANSansWeb_Medium.woff',
      weight: '500',
    },
    {
      path: './fonts/IRANSansWeb_Bold.woff',
      weight: '700',
    },
  ],
})

export const metadata: Metadata = {
  title: 'هتل ارگ جدید یزد',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Also supported but less commonly used
  // interactiveWidget: 'resizes-visual',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={iranSans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
